version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sch_matrix_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/data:/workspace/app/data
      - ./backend/app/static/audio:/workspace/app/static/audio
      - ./frontend:/workspace/frontend:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sch_matrix_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: sch_matrix_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - frontend
